FROM docker.io/library/fedora:34
ARG FLUTTER_CHANNEL

RUN dnf update --refresh -y \
    && dnf install curl git unzip findutils which -y \
    && useradd -ms /bin/bash flutterbuilder

USER flutterbuilder
WORKDIR /home/flutterbuilder

ENV PATH "$PATH:/home/flutterbuilder/sdk/flutter/bin"

RUN git clone https://github.com/flutter/flutter.git -b ${FLUTTER_CHANNEL} /home/flutterbuilder/sdk/flutter \
    && flutter config --no-analytics --enable-web --no-enable-linux-desktop --no-enable-macos-desktop --no-enable-windows-desktop --no-enable-android --no-enable-ios --no-enable-fuchsia \
    && flutter channel ${FLUTTER_CHANNEL} && flutter upgrade \
    && flutter --version \
    # create a temporary project & build it to trigger dependency downloads
    && flutter create --platforms web tmp \
    && cd tmp \
    && flutter build web \
    && cd .. \
    && rm -rf tmp
